title: 'The Rivers'
description: 'Homepage of The Rivers - the groove-driven Oxford based acapella group'
author: 'Miles Phillips'

sass:
  style: compressed

assets_path: '' 

collections:
  projects:
