---
title: The Rivers
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: false
  uploads:
    title: Uploads
    output: true
description: Homepage of The Rivers - the groove-driven Oxford based acapella group
author: Miles Phillips
sass:
  style: compressed
assets_path: ''
exclude:
- assets/vendor
