brand:
  name: The Rivers
  logo: <img src='/assets/img/logo.png'></img>
menu-string: 

nav:
  - title: Gigs
    url: '#services'
  - title: Watch
    url: '#portfolio'
  - title: About
    url: '#about'
  - title: Contact
    url: '#contact'

copyright: Copyright &copy; The Rivers 2019

social-buttons:
  - icon: fa fa-twitter
    url: 'https://twitter.com/riversacapella' 
  - icon: fa fa-facebook
    url: 'https://www.facebook.com/theriversacapella/'

quicklinks:

modal:
  date-string: 'Date: '
  client-string: 'Client: '
  category-string: 'Category: '
  close-icon: 'fa fa-times'
  close-string: 'Close Project'
